name: 'Dartanalyzer annotations'
description: 'Creates annotations from dartanalyzer outputs.'
inputs:
  check_name:
    description: "The name of the check run to add annotations to.
        This should be the same as the job that uses this action."
    required: true
  commit_sha:
    description: "Commit to attach the check to. If the trigger is `push`,
        this should just be github.sha. If the trigger is `pull_request`,
        this should be the github.event.pull_request.head.sha"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'blue'  
